### ISSUE TITLE
Nettsiden... tanken bak

### ISSUE THREAD

**Issue by fuzzy76** [kodeklubben-tromso/kodeklubben-tromso.github.io#1]
Jeg kunne tenkt meg å utvide nettsiden litt, men må forsikre meg om at jeg ikke trår i beina på noen. Det ser ut som at siden er generert med en eller annen generator...? Er det interesse for at jeg porter siden slik den er nå til [Jekyll](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/) slik at man lettere kan lage en meny med undersider som alle ser like ut? Hvis noen helst foretrekker at den forblir slik den er tåler jeg å høre det også. :)

**Comment by Gronnesby** [comment]
Du skal bare utvide nettsiden. Først så ble koden generert gjennom github pages, senere så har jeg bare skrevet statisk HTML og CSS over dette. Bare port den over til Jekyll, vi har ikke mye tid selv til å vedlikeholde siden, så hjelp her er hjertelig velkommen :)

**Comment by fuzzy76** [comment]
Jekyll-porten er live. :)
